[package]
name = "networking"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.4"
protos = { path = "../protos" }
tracing = "0.1.41"
anyhow = "1.0.95"
tokio = { version = "1.43.0", features = ["net"] }
