[package]
name = "observer"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
networking = { path = "../networking" }
protos = { path = "../protos" }
tokio = { version = "1.43.0", features = ["rt", "macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
